---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-direnv
description: Install direnv through ansible
tags:
  - ansible
  - ansible-role
  - direnv
github:
  has_issues: true
  has_projects: false
  has_wiki: false
